### ISSUE TITLE
support for /// comment style

### ISSUE THREAD

**Issue by defunctzombie** [jdeal/doctor#18]
Is there an example of how to support the following comment style

``` javascript
/// blah blah blah
/// @param {Array} blar
function foo(bar) {
}
```

I prefer this style to the crazy \* style :).

This project looks awesome. Hope to use this in an upcoming tool I am working on!

**Comment by jdeal** [comment]
Is there a significance to the extra slash? Because this:

``` js
// blah blah blah
// @param {Array} blar
function foo(bar) {
}
```

should work just fine. I should make a specific test for that, but I know I coded for it.

**Comment by jdeal** [comment]
Oh, and thanks for the complement. Hopefully it holds up to closer scrutiny. :-)

**Comment by defunctzombie** [comment]
It was a comment style I picked up way back from c# and is an alternative to the typical /*\* javadoc style that I find more visually appealing and takes less vertical space :)

http://geekswithblogs.net/ewright/archive/2004/05/27/5455.aspx
http://www.cs.rit.edu/~cs4/Documents/progstyle-cpp-2009.html

At the end of the day it is just preference.

**Comment by jdeal** [comment]
I made the default transform ignore extra slashes, so you should be able to use this style now.

**Comment by defunctzombie** [comment]
awesome! thanks
