### ISSUE TITLE
With doctor generated doctor docs?

### ISSUE THREAD

**Issue by mlegenhausen** [jdeal/doctor#2]
I am missing an example. Why you not simply generate the docs for doctor with doctor and add a link to the read me?

**Comment by jdeal** [comment]
I was in the process of doing this, when doctor was prematurely announced on the node.js mailing list. As stated elsewhere, there's still work to be done. But, so far, here you go:

http://jdeal.github.com/doctor/doc/

This was generated from the repository clone with:

```
doctor lib/*.js -v default -o ../pages/doctor/doc
```

(Where ../pages/doctor/doc is my gh-pages branch.)

**Comment by mlegenhausen** [comment]
Thanks, looks great is much more clear than other doc generators
