### ISSUE TITLE
Tag parsing issue

### ISSUE THREAD

**Issue by heff** [jdeal/doctor#22]
At first glance it looks like it doesn't support tags with no value. Any idea what's happening here?

> doctor player.js
> stack:
> Error: Error parsing comment tag in file player:21 - SyntaxError: Expected end of > line or whitespace but "@" found., comment text: An instance of the `Video.Player` > class is created when any of the Video.js setup methods are used to initialize a > video.
> 
> ``` js
> var myPlayer = Video('example_video_1');
> ```
> 
> In the follwing example, the `data-setup` attribute tells the Video.js library to > create a player instance when the library is ready.
> 
> ``` html
> <video id="example_video_1" data-setup='{}' controls>
>   <source src="my-source.mp4" type="video/mp4">
> </video>
> ```
> 
> After an instance has been created it can be accessed globally using `Video(> 'example_video_1')`.
> 
> @class
> @extends vjs.Component
>     at commentTransform (/usr/local/lib/node_modules/doctor/transform/default.> js:166:13)
>     at Object.rules.push.transform (> /usr/local/lib/node_modules/doctor/transform/default.js:179:16)
>     at eachNodeRule (/usr/local/lib/node_modules/doctor/lib/transform.js:26:14)
>     at eachNode (/usr/local/lib/node_modules/doctor/lib/nice-ast.js:496:7)
>     at cb.type (/usr/local/lib/node_modules/doctor/lib/nice-ast.js:54:7)
>     at walk (/usr/local/lib/node_modules/doctor/lib/nice-ast.js:26:5)
>     at /usr/local/lib/node_modules/doctor/lib/nice-ast.js:32:7
>     at Array.forEach (native)
>     at walk (/usr/local/lib/node_modules/doctor/lib/nice-ast.js:31:15)
>     at /usr/local/lib/node_modules/doctor/lib/nice-ast.js:32:7

**Comment by jdeal** [comment]
Sorry for reacting so slow...

Can you supply a minimal file like your `player.js` that breaks? I'm not sure I'm following the above description. This:

`Video(> 'example_video_1')`

doesn't look valid to me. Maybe if I see a (minimal) breaking file, I'll understand.

**Comment by heff** [comment]
No problem. That file's changed a bunch now so I don't think I can get you an example, but if it comes up again I will. I'm not sure where the angle bracket is coming from but I don't think it's my code. My only thought here is maybe there's an issue with github code formatting, with the ```

closing
