### ISSUE TITLE
Literal object programming support

### ISSUE THREAD

**Issue by alexstrat** [jdeal/doctor#9]
Hi,

I came across _doctor_ while searching an easy hackable alternative to JsDoc, and I think I found something impressive !

Actually, I wanted to quickly generate a documentation for my semester project ([KadOH](https://github.com/jinroh/kadoh)) before present it, but I think that _doctor_ does not yet support literal prototype, does it ?

I mean by _literal prototype_ something like that :

``` js
/**
 * Document the constructor
 */
Person = function (name) {};

Person.prototype = {

  /**
   * Document the #setName
   */
  setName: function (name) {},

  /**
   * Document the #getName
   */
  getName: function () {}
};
```

Have some hints on how I can make doctor support literal prototype ? Where should I start ? I hope not in the grammar : i'm affraid of it.. 

Moreover I use a inheritence framework ([Klass](http://dustindiaz.com/klass)) – that looks like _literal object programming_ (check [here](https://github.com/jinroh/kadoh/blob/experimental/lib/client/node.js#L28) an example). Are the inheritence JsDoc tags **@augments** already supported ?

**Comment by jdeal** [comment]
Thanks!

You came to the right place, but the party hasn't quite started yet. I have a lot of work to do to finish doctor and make it hacker-friendly. In the meantime...

You do not have to mess with the grammar for writing new rules. The javascript grammar file is for raw js grammar processing, and the comment grammar is for creating new commenting conventions.

You can look at report/default.js for all the current rules that create a report. You'd need to add a new rule for your the literal prototype convention. You can either fork doctor and add it into default.js, or you can just create your own doctor-rules.js (or whatever) and reference that your rule(s) from the command-line something like this:

```
doctor path-to-your-project/lib/*.js -r default -r path-to-your-custom-rules/doctor-rules.js -o your-output-path 
```

If you supply your own rules file like above, it will not even use the default. Hence, you have to add the -r default to make sure the default rules are used as well.

As far as writing the actual rule, the default.js rules need to be refactored as some are written in a simpler style than others. Look at the rules that have node.likeSource in them for the simplest examples. likeSource allows you to compare a node to a string of js source. So something like:

``` js
module.exports = [
  {
    type: 'assign',
    match: function (node) {
      return node.likeSource('__name__.prototype = {}');
    }
    report: function (node, report) {
      // use node.lispify() to inspect the node while building your rule.
      // return report item(s) here
    }
  }
];
```

would match the convention you're describing. In the report function, you'll have to rip apart the ast of the node and pull out the info you need. The node.lispify() function is helpful to inspect a node in compact form.

Note that a custom rules module needs to export an array of rules.

Note that comments are not currently collected for every node type. If comments are missing for your convention, let me know, and I'll add it in. I plan on collecting comments for every node type, but just haven't gotten to it yet.

**Comment by jdeal** [comment]
Note also that because of issue #3, while debugging your rules, any console.logs will show up twice.

**Comment by jdeal** [comment]
I went ahead and added the literal prototype support, per #10 and #11. You can look at the commit to see hacking tips.

Doctor does support the @extends tag, which is a synonym for @augments. I'd like to eventually avoid that tag though and have it built into some conventions.

Closing this issue per its title. If you want to open up another issue specific to Klass, feel free. (It will probably be low on the priority list though.)

**Comment by alexstrat** [comment]
Wohh ! Nice reactivity, thanks a lot !

I was actually trying to go into it, just by reading, but it's not obvious to understand mentally what things like `node.nodes[2].nodes` could refer to !! I should definitely use `node.lispify()`..

Yes Klass patterns support is a very specific usage and not a priority. I'll try to implement it for my use. If I manage to make this work with **@extends** (or not, because it's already specified in the code), I'll be very happy and it will put an end to few months long wandering across different documentation generators !! :)

I'll post an issue about it to keep this in mind.

**Comment by jdeal** [comment]
I can't promise to always be so reactive, but if you find other missing/broken things, just open up issues, and I'll do what I can. This tool is actively being used in a large project, so as long as the project continues, doctor will continue to get better. But making doctor better is certainly not the primary goal of the project.

Yes, it takes a bit to wrap your head around the abstractness of the abstract syntax tree. But likeSource and lispify help, and maybe as time goes on, additional helpers can make things easier.
